version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key-123
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=salon
      - UPLOAD_FOLDER=/app/static/uploads
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - uploads_volume:/app/static/uploads
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=salon
      - PGDATA=/var/lib/postgresql/data/pgdata  # Thêm biến môi trường PGDATA
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d salon"]  # Thêm tên database
      interval: 10s
      timeout: 5s
      retries: 10  # Tăng số lần thử lại
      start_period: 30s  # Thêm thời gian chờ khởi tạo ban đầu
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_volume: