services:
  - type: web
    name: salon-management
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: salon-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: "salon_uploads"
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: salon-db
    databaseName: salon
    user: salon_user
    plan: free
